name: Daily Notion Update

on:
  schedule:
    - cron: "0 8 * * *" # 매일 아침 8시에 실행
  workflow_dispatch:

jobs:
  update_notion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create JSON from secret
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "tistory.json" # 생성할 파일 이름
          json: ${{ secrets.GA_CREDENTIALS_FILE }}

      - name: Create config.py file
        run: |
          cat > config.py << EOF
          # 자동 생성된 config.py 파일
          GA_CREDENTIALS_FILE = "tistory.json"
          # 필요한 다른 시크릿 변수들도 추가할 수 있습니다
          GA_PROPERTY_ID = "${{ secrets.GA_PROPERTY_ID }}"
          NOTION_TOKEN = "${{ secrets.NOTION_TOKEN }}"
          NOTION_PARENT_PAGE_ID = "${{ secrets.NOTION_PARENT_PAGE_ID }}"
          EOF
        shell: bash

      - name: Run Notion Update Script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PARENT_PAGE_ID: ${{ secrets.NOTION_PARENT_PAGE_ID }}
          GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}
        run: |
          python main.py
